image: cypress/base:10

stages:
  - install
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - /root/.cache/Cypress
    - node_modules

install:
  stage: install
  script:
    - npm ci

test:
  stage: test
  script:
    - npm run test
    
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
      - cypress/results/
    expire_in: 1 day