stages:
  - build
  - test

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress
    - node_modules

install:
  image: cypress/base:10
  stage: build

  script:
    - npm ci
    - $(npm bin)/cypress cache path
    - $(npm bin)/cypress cache list
    - $(npm bin)/cypress verify

cypress-e2e:
  image: cypress/base:10
  stage: test
  script:
    - $(npm bin)/cypress run --record --key f1bfa0a0-cfa6-4e6f-812d-71fecc264948
  artifacts:
    expire_in: 1 week
    when: always
    paths:
    - cypress/screenshots
    - cypress/videos
    - cypress/results

cypress-e2e-chrome:
  image: cypress/browsers:chrome67
  stage: test
  script:
    - $(npm bin)/cypress run --record --key f1bfa0a0-cfa6-4e6f-812d-71fecc264948 --browser chrome
  artifacts:
    expire_in: 1 week
    when: always
    paths:
    - cypress/screenshots
    - cypress/results
